// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _420_5W6_VL_Projet.Models;

#nullable disable

namespace _420_5W6_VL_Projet.Migrations
{
    [DbContext(typeof(ReeditContext))]
    [Migration("20221101190057_temp-dimension")]
    partial class tempdimension
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_420_5W6_VL_Projet.Models.Entities.Comment", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Lid")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Cid");

                    b.HasIndex("Lid");

                    b.HasIndex("Uid");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("_420_5W6_VL_Projet.Models.Entities.Link", b =>
                {
                    b.Property<int>("Lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Lid");

                    b.HasIndex("Uid");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("_420_5W6_VL_Projet.Models.Entities.User", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Uid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Uid = 1,
                            Email = "projetadmin@gmail.com",
                            Password = "Admin123!",
                            Username = "projet_admin"
                        },
                        new
                        {
                            Uid = 2,
                            Email = "projetuser@gmail.com",
                            Password = "User123!",
                            Username = "projet_user"
                        });
                });

            modelBuilder.Entity("_420_5W6_VL_Projet.Models.Entities.Vote", b =>
                {
                    b.Property<int>("Vid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Lid")
                        .HasColumnType("int");

                    b.Property<int?>("LinkLid")
                        .HasColumnType("int");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.Property<int?>("UserUid")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Vid");

                    b.HasIndex("LinkLid");

                    b.HasIndex("UserUid");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("_420_5W6_VL_Projet.Models.Entities.Comment", b =>
                {
                    b.HasOne("_420_5W6_VL_Projet.Models.Entities.Link", "Link")
                        .WithMany("Comments")
                        .HasForeignKey("Lid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_420_5W6_VL_Projet.Models.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_420_5W6_VL_Projet.Models.Entities.Link", b =>
                {
                    b.HasOne("_420_5W6_VL_Projet.Models.Entities.User", "User")
                        .WithMany("Links")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("_420_5W6_VL_Projet.Models.Entities.Vote", b =>
                {
                    b.HasOne("_420_5W6_VL_Projet.Models.Entities.Link", null)
                        .WithMany("Votes")
                        .HasForeignKey("LinkLid");

                    b.HasOne("_420_5W6_VL_Projet.Models.Entities.User", null)
                        .WithMany("Votes")
                        .HasForeignKey("UserUid");
                });

            modelBuilder.Entity("_420_5W6_VL_Projet.Models.Entities.Link", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("_420_5W6_VL_Projet.Models.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Links");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
